apiVersion: v1
data:
  config_tcp.js: |-
    {
      "graphiteHost": "127.0.0.1",
      "graphitePort": 2003,
      "port": 8125,
      "flushInterval": 10000,
      "servers": [{
        "server": "./servers/tcp",
        "address": "0.0.0.0",
        "port": 8125
      }]
    }
  config_udp.js: |-
    {
      "graphiteHost": "127.0.0.1",
      "graphitePort": 2003,
      "port": 8125,
      "flushInterval": 10000,
      "servers": [{
        "server": "./servers/udp",
        "address": "0.0.0.0",
        "port": 8125
      }]
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: graphite-sitespeed
    app.kubernetes.io/name: graphite
  name: graphite-sitespeed-statsd-configmap
  namespace: sitespeed